//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crawler2._0.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting free worker thread.
        /// </summary>
        internal static string Awaiting_worker_String {
            get {
                return ResourceManager.GetString("Awaiting_worker_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will make the process much slower, are you sure you want to enable this?.
        /// </summary>
        internal static string Download_covers_String {
            get {
                return ResourceManager.GetString("Download_covers_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download List({0}).
        /// </summary>
        internal static string Download_list_String {
            get {
                return ResourceManager.GetString("Download_list_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages: .
        /// </summary>
        internal static string manga_Pages_String {
            get {
                return ResourceManager.GetString("manga_Pages_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site: .
        /// </summary>
        internal static string manga_Site_String {
            get {
                return ResourceManager.GetString("manga_Site_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: .
        /// </summary>
        internal static string manga_Title_String {
            get {
                return ResourceManager.GetString("manga_Title_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string MangaDownloadFinishedEvent_Downloaded_string {
            get {
                return ResourceManager.GetString("MangaDownloadFinishedEvent_Downloaded_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://i.nhentai.net/galleries/{0}/{1}.
        /// </summary>
        internal static string nhentai_url_String {
            get {
                return ResourceManager.GetString("nhentai_url_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string PictureDownloadStartedEvent_Downloading {
            get {
                return ResourceManager.GetString("PictureDownloadStartedEvent_Downloading", resourceCulture);
            }
        }
    }
}
